<?php
/**
 * Terms of Service
 */

ob_start();
?>

<div class="row justify-content-center">
    <div class="col-lg-9 col-xl-8">
        <div class="card">
            <div class="card-body p-4 p-md-5">
                <h2 class="mb-4">Terms of Service</h2>
                <p class="text-muted mb-4">Last updated: March 2026</p>

                <h5>1. Acceptance of Terms</h5>
                <p>By accessing and using MyExpenses ("the Service"), provided by VisionQuest Services LLC ("we", "us", "our"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use the Service.</p>

                <h5>2. Description of Service</h5>
                <p>MyExpenses is an expense tracking and management application that allows users to record, categorize, and analyze personal and business expenses. The Service includes features such as expense entry, recurring expense management, reporting, and data export.</p>

                <h5>3. User Accounts</h5>
                <p>To use the Service, you must create an account by providing accurate and complete registration information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.</p>

                <h5>4. User Responsibilities</h5>
                <p>You agree to:</p>
                <ul>
                    <li>Use the Service only for lawful purposes and in accordance with these Terms.</li>
                    <li>Provide accurate and truthful financial information.</li>
                    <li>Keep your account information up to date.</li>
                    <li>Not attempt to gain unauthorized access to any portion of the Service.</li>
                    <li>Not use the Service to transmit any harmful or malicious content.</li>
                </ul>

                <h5>5. Data Ownership</h5>
                <p>You retain full ownership of all financial data and content you enter into the Service. We do not claim any ownership rights over your data. You may export or delete your data at any time.</p>

                <h5>6. Privacy</h5>
                <p>Your use of the Service is also governed by our <a href="/privacy">Privacy Policy</a>, which describes how we collect, use, and protect your personal information.</p>

                <h5>7. Service Availability</h5>
                <p>We strive to keep the Service available at all times but do not guarantee uninterrupted access. We may temporarily suspend the Service for maintenance, updates, or unforeseen circumstances. We are not liable for any loss resulting from Service downtime.</p>

                <h5>8. Limitation of Liability</h5>
                <p>The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. VisionQuest Services LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the Service. Our total liability shall not exceed the amount paid by you, if any, for access to the Service during the twelve months preceding the claim.</p>

                <h5>9. Disclaimer</h5>
                <p>MyExpenses is a tool for personal expense tracking and is not a substitute for professional financial, tax, or accounting advice. We make no representations regarding the accuracy of any calculations or reports generated by the Service. You are solely responsible for verifying the accuracy of your financial records.</p>

                <h5>10. Modifications to Terms</h5>
                <p>We reserve the right to modify these Terms at any time. Changes will be posted on this page with an updated revision date. Your continued use of the Service after changes are posted constitutes acceptance of the modified Terms.</p>

                <h5>11. Termination</h5>
                <p>We may suspend or terminate your access to the Service at any time, with or without cause, and with or without notice. Upon termination, your right to use the Service ceases immediately. You may request export of your data prior to account termination.</p>

                <h5>12. Governing Law</h5>
                <p>These Terms shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of law provisions.</p>

                <h5>13. Contact</h5>
                <p>If you have any questions about these Terms of Service, please contact us at:</p>
                <p>
                    <strong>VisionQuest Services LLC</strong><br>
                    Email: support@visionquestservices.com
                </p>
            </div>
        </div>
    </div>
</div>

<?php
$content = ob_get_clean();
$title   = 'Terms of Service';
require VIEW_PATH . '/layouts/app.php';
?>
